import type { ModelDefinition } from "./types";

export const MODEL_CATALOG: ModelDefinition[] = [
  // ─── OpenAI ───
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    pricing: { inputPer1M: 2.0, outputPer1M: 8.0, cachedInputPer1M: 0.5, batchMultiplier: 0.5 },
    bedrockPricing: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 32_768,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "openai",
    pricing: { inputPer1M: 0.4, outputPer1M: 1.6, cachedInputPer1M: 0.1, batchMultiplier: 0.5 },
    bedrockPricing: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 32_768,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "openai",
    pricing: { inputPer1M: 0.1, outputPer1M: 0.4, cachedInputPer1M: 0.025, batchMultiplier: 0.5 },
    bedrockPricing: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 32_768,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "o3",
    name: "o3",
    provider: "openai",
    pricing: { inputPer1M: 10.0, outputPer1M: 40.0, cachedInputPer1M: 2.5, batchMultiplier: null },
    bedrockPricing: null,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: true,
    reasoningTokenMultiplier: 3,
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "openai",
    pricing: { inputPer1M: 1.1, outputPer1M: 4.4, cachedInputPer1M: 0.275, batchMultiplier: 0.5 },
    bedrockPricing: null,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: true,
    reasoningTokenMultiplier: 2,
  },

  // ─── Anthropic ───
  {
    id: "claude-opus-4",
    name: "Claude Opus 4",
    provider: "anthropic",
    pricing: { inputPer1M: 15.0, outputPer1M: 75.0, cachedInputPer1M: 1.875, batchMultiplier: 0.5 },
    bedrockPricing: { inputPer1M: 15.0, outputPer1M: 75.0, cachedInputPer1M: 1.875, batchMultiplier: null },
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "anthropic",
    pricing: { inputPer1M: 3.0, outputPer1M: 15.0, cachedInputPer1M: 0.375, batchMultiplier: 0.5 },
    bedrockPricing: { inputPer1M: 3.0, outputPer1M: 15.0, cachedInputPer1M: 0.375, batchMultiplier: null },
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "claude-haiku-3.5",
    name: "Claude Haiku 3.5",
    provider: "anthropic",
    pricing: { inputPer1M: 0.8, outputPer1M: 4.0, cachedInputPer1M: 0.08, batchMultiplier: 0.5 },
    bedrockPricing: { inputPer1M: 0.8, outputPer1M: 4.0, cachedInputPer1M: 0.08, batchMultiplier: null },
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },

  // ─── Google ───
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    pricing: { inputPer1M: 1.25, outputPer1M: 10.0, cachedInputPer1M: 0.3125, batchMultiplier: null },
    bedrockPricing: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: true,
    reasoningTokenMultiplier: 2,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    pricing: { inputPer1M: 0.15, outputPer1M: 0.6, cachedInputPer1M: 0.0375, batchMultiplier: null },
    bedrockPricing: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: true,
    reasoningTokenMultiplier: 1.5,
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    pricing: { inputPer1M: 0.1, outputPer1M: 0.4, cachedInputPer1M: 0.025, batchMultiplier: null },
    bedrockPricing: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },

  // ─── DeepSeek ───
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "deepseek",
    pricing: { inputPer1M: 0.27, outputPer1M: 1.1, cachedInputPer1M: 0.07, batchMultiplier: null },
    bedrockPricing: null,
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "deepseek",
    pricing: { inputPer1M: 0.55, outputPer1M: 2.19, cachedInputPer1M: 0.14, batchMultiplier: null },
    bedrockPricing: null,
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    supportsToolCalls: false,
    supportsPromptCaching: true,
    toolDefinitionOverhead: 0,
    isReasoningModel: true,
    reasoningTokenMultiplier: 3,
  },

  // ─── Meta ───
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    provider: "meta",
    pricing: { inputPer1M: 0.17, outputPer1M: 0.17, cachedInputPer1M: null, batchMultiplier: null },
    bedrockPricing: { inputPer1M: 0.34, outputPer1M: 0.34, cachedInputPer1M: null, batchMultiplier: null },
    contextWindow: 512_000,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    provider: "meta",
    pricing: { inputPer1M: 0.27, outputPer1M: 0.35, cachedInputPer1M: null, batchMultiplier: null },
    bedrockPricing: { inputPer1M: 0.54, outputPer1M: 0.70, cachedInputPer1M: null, batchMultiplier: null },
    contextWindow: 1_048_576,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },

  // ─── Mistral ───
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "mistral",
    pricing: { inputPer1M: 2.0, outputPer1M: 6.0, cachedInputPer1M: null, batchMultiplier: null },
    bedrockPricing: { inputPer1M: 4.0, outputPer1M: 12.0, cachedInputPer1M: null, batchMultiplier: null },
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },
  {
    id: "mistral-small",
    name: "Mistral Small",
    provider: "mistral",
    pricing: { inputPer1M: 0.1, outputPer1M: 0.3, cachedInputPer1M: null, batchMultiplier: null },
    bedrockPricing: { inputPer1M: 0.2, outputPer1M: 0.6, cachedInputPer1M: null, batchMultiplier: null },
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    supportsToolCalls: true,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 150,
    isReasoningModel: false,
  },

  // ─── Cohere (Embedding & Reranking) ───
  {
    id: "cohere-embed-v3",
    name: "Cohere Embed v3",
    provider: "cohere",
    pricing: { inputPer1M: 0.1, outputPer1M: 0, cachedInputPer1M: null, batchMultiplier: null },
    bedrockPricing: { inputPer1M: 0.1, outputPer1M: 0, cachedInputPer1M: null, batchMultiplier: null },
    contextWindow: 512,
    maxOutputTokens: 0,
    supportsToolCalls: false,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 0,
    isReasoningModel: false,
    isEmbeddingModel: true,
    embeddingPricePer1M: 0.1,
  },
  {
    id: "cohere-rerank-v3",
    name: "Cohere Rerank v3",
    provider: "cohere",
    pricing: { inputPer1M: 2.0, outputPer1M: 0, cachedInputPer1M: null, batchMultiplier: null },
    bedrockPricing: { inputPer1M: 2.0, outputPer1M: 0, cachedInputPer1M: null, batchMultiplier: null },
    contextWindow: 4_096,
    maxOutputTokens: 0,
    supportsToolCalls: false,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 0,
    isReasoningModel: false,
  },

  // ─── OpenAI Embeddings ───
  {
    id: "text-embedding-3-small",
    name: "text-embedding-3-small",
    provider: "openai",
    pricing: { inputPer1M: 0.02, outputPer1M: 0, cachedInputPer1M: null, batchMultiplier: 0.5 },
    bedrockPricing: null,
    contextWindow: 8_191,
    maxOutputTokens: 0,
    supportsToolCalls: false,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 0,
    isReasoningModel: false,
    isEmbeddingModel: true,
    embeddingPricePer1M: 0.02,
  },
  {
    id: "text-embedding-3-large",
    name: "text-embedding-3-large",
    provider: "openai",
    pricing: { inputPer1M: 0.13, outputPer1M: 0, cachedInputPer1M: null, batchMultiplier: 0.5 },
    bedrockPricing: null,
    contextWindow: 8_191,
    maxOutputTokens: 0,
    supportsToolCalls: false,
    supportsPromptCaching: false,
    toolDefinitionOverhead: 0,
    isReasoningModel: false,
    isEmbeddingModel: true,
    embeddingPricePer1M: 0.13,
  },
];

export function getModelById(id: string): ModelDefinition | undefined {
  return MODEL_CATALOG.find((m) => m.id === id);
}

export function getModelsByProvider(provider: ModelProvider): ModelDefinition[] {
  return MODEL_CATALOG.filter((m) => m.provider === provider);
}

export function buildModelMap(): Map<string, ModelDefinition> {
  return new Map(MODEL_CATALOG.map((m) => [m.id, m]));
}

// Re-export for convenience
import type { ModelProvider } from "./types";
