import type { WorkflowPreset } from "./types";
import { DEFAULTS } from "./constants";

export const WORKFLOW_PRESETS: WorkflowPreset[] = [
  // ─── Interview Scenario: Payments Data Platform Copilot (RAG) ───
  {
    id: "payments-copilot-rag",
    name: "Payments Data Copilot (RAG)",
    description:
      "Fraud investigation copilot with RAG, 12 domain tools, and guardrails. Based on real interview demo.",
    costMetricLabel: "Cost per fraud investigation query",
    workflow: {
      pattern: "sequential",
      agents: [
        {
          id: "copilot",
          name: "Investigation Copilot",
          modelId: "claude-sonnet-4",
          role: "worker",
          avgStepsPerTask: 3,
          avgToolCallsPerStep: 2,
          toolDefinitionCount: 12,
          systemPromptTokens: 2000,
          avgInputTokensPerStep: 2500,
          avgOutputTokensPerStep: 800,
          reflectionPasses: 0,
          contextStrategy: "full-history",
          cacheableInputFraction: 0.5,
          stackComponents: [
            {
              id: "embedding",
              name: "Document Embedding",
              category: "embedding",
              modelId: "text-embedding-3-small",
              avgInputTokens: 500,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
            },
            {
              id: "vector-search",
              name: "Vector Search (Pinecone)",
              category: "search",
              avgInputTokens: 0,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
              fixedCostPerCall: 0.00008,
            },
            {
              id: "reranking",
              name: "Reranking (Cohere v3)",
              category: "reranking",
              modelId: "cohere-rerank-v3",
              avgInputTokens: 4000,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
            },
            {
              id: "generation",
              name: "LLM Generation (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 4200,
              avgOutputTokens: 850,
              cacheable: true,
              cacheHitRate: 0.6,
              callsPerInvocation: 3,
            },
            {
              id: "tool-calls",
              name: "Tool Call Overhead",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 900,
              avgOutputTokens: 200,
              cacheable: true,
              cacheHitRate: 0.8,
              callsPerInvocation: 6,
            },
            {
              id: "guardrails",
              name: "Guardrails / PII Check",
              category: "guardrail",
              modelId: "claude-haiku-3.5",
              avgInputTokens: 1200,
              avgOutputTokens: 100,
              cacheable: true,
              cacheHitRate: 0.9,
              callsPerInvocation: 1,
            },
          ],
        },
      ],
      errorRetryRate: 0.03,
      orchestrationOverheadTokens: 0,
    },
    usage: { tasksPerDay: 500, usersCount: 20, daysPerMonth: 22 },
    infra: {
      vectorDbMonthlyCost: 70,
      observabilityMonthlyCost: 50,
      computeMonthlyCost: 0,
      customItems: [],
    },
  },

  // ─── Interview Scenario: Semantic Router ───
  {
    id: "semantic-router",
    name: "Context-Aware Semantic Router",
    description:
      "Cost-optimized LLM routing: classify query complexity, route to appropriate model tier.",
    costMetricLabel: "Cost per routing decision + routed query",
    workflow: {
      pattern: "sequential",
      agents: [
        {
          id: "classifier",
          name: "Query Classifier",
          modelId: "claude-haiku-3.5",
          role: "classifier",
          avgStepsPerTask: 1,
          avgToolCallsPerStep: 0,
          toolDefinitionCount: 0,
          systemPromptTokens: 800,
          avgInputTokensPerStep: 500,
          avgOutputTokensPerStep: 50,
          reflectionPasses: 0,
          contextStrategy: "stateless",
          cacheableInputFraction: 0.8,
          stackComponents: [
            {
              id: "classify",
              name: "Intent Classification (Haiku)",
              category: "routing",
              modelId: "claude-haiku-3.5",
              avgInputTokens: 1300,
              avgOutputTokens: 50,
              cacheable: true,
              cacheHitRate: 0.85,
              callsPerInvocation: 1,
            },
          ],
        },
        {
          id: "responder",
          name: "Response Generator",
          modelId: "claude-sonnet-4",
          role: "worker",
          avgStepsPerTask: 1,
          avgToolCallsPerStep: 0,
          toolDefinitionCount: 3,
          systemPromptTokens: 1500,
          avgInputTokensPerStep: 2000,
          avgOutputTokensPerStep: 600,
          reflectionPasses: 0,
          contextStrategy: "stateless",
          cacheableInputFraction: 0.5,
          stackComponents: [
            {
              id: "generation",
              name: "LLM Response (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 3500,
              avgOutputTokens: 600,
              cacheable: true,
              cacheHitRate: 0.5,
              callsPerInvocation: 1,
            },
          ],
        },
      ],
      errorRetryRate: 0.02,
      orchestrationOverheadTokens: 50,
    },
    usage: { tasksPerDay: 2000, usersCount: 100, daysPerMonth: 30 },
    infra: {
      vectorDbMonthlyCost: 0,
      observabilityMonthlyCost: 30,
      computeMonthlyCost: 0,
      customItems: [],
    },
  },

  // ─── Interview Scenario: PII Proxy Agent ───
  {
    id: "pii-proxy",
    name: "Zero-Trust PII Proxy",
    description:
      "PII detection and masking layer that wraps any LLM call. Shows the overhead cost of privacy compliance.",
    costMetricLabel: "PII overhead cost per query",
    workflow: {
      pattern: "sequential",
      agents: [
        {
          id: "pii-agent",
          name: "PII Proxy Agent",
          modelId: "claude-sonnet-4",
          role: "worker",
          avgStepsPerTask: 1,
          avgToolCallsPerStep: 0,
          toolDefinitionCount: 2,
          systemPromptTokens: 1200,
          avgInputTokensPerStep: 2000,
          avgOutputTokensPerStep: 700,
          reflectionPasses: 0,
          contextStrategy: "stateless",
          cacheableInputFraction: 0.6,
          stackComponents: [
            {
              id: "pii-detect",
              name: "PII Detection (NER)",
              category: "guardrail",
              modelId: "claude-haiku-3.5",
              avgInputTokens: 2000,
              avgOutputTokens: 300,
              cacheable: true,
              cacheHitRate: 0.7,
              callsPerInvocation: 1,
            },
            {
              id: "generation",
              name: "LLM Generation (sanitized)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 3200,
              avgOutputTokens: 700,
              cacheable: true,
              cacheHitRate: 0.5,
              callsPerInvocation: 1,
            },
            {
              id: "pii-unmask",
              name: "PII Unmasking",
              category: "guardrail",
              modelId: "claude-haiku-3.5",
              avgInputTokens: 1000,
              avgOutputTokens: 700,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
            },
          ],
        },
      ],
      errorRetryRate: 0.01,
      orchestrationOverheadTokens: 0,
    },
    usage: { tasksPerDay: 1000, usersCount: 50, daysPerMonth: 30 },
    infra: {
      vectorDbMonthlyCost: 0,
      observabilityMonthlyCost: 20,
      computeMonthlyCost: 0,
      customItems: [],
    },
  },

  // ─── Multi-Agent Research (LangGraph) ───
  {
    id: "multi-agent-research",
    name: "Multi-Agent Research (LangGraph)",
    description:
      "Planner delegates to parallel researchers, then synthesizes results. Hierarchical pattern.",
    costMetricLabel: "Cost per research task",
    workflow: {
      pattern: "hierarchical",
      agents: [
        {
          id: "planner",
          name: "Research Planner",
          modelId: "claude-sonnet-4",
          role: "orchestrator",
          avgStepsPerTask: 2,
          avgToolCallsPerStep: 0,
          toolDefinitionCount: 4,
          systemPromptTokens: 2000,
          avgInputTokensPerStep: 3000,
          avgOutputTokensPerStep: 1000,
          reflectionPasses: 1,
          contextStrategy: "full-history",
          cacheableInputFraction: 0.5,
          stackComponents: [
            {
              id: "planning",
              name: "Task Planning (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 5000,
              avgOutputTokens: 1000,
              cacheable: true,
              cacheHitRate: 0.6,
              callsPerInvocation: 3,
            },
          ],
        },
        {
          id: "researcher-1",
          name: "Web Researcher",
          modelId: "gpt-4.1-mini",
          role: "worker",
          avgStepsPerTask: 4,
          avgToolCallsPerStep: 2,
          toolDefinitionCount: 5,
          systemPromptTokens: 1500,
          avgInputTokensPerStep: 3000,
          avgOutputTokensPerStep: 1500,
          reflectionPasses: 0,
          contextStrategy: "sliding-window",
          slidingWindowSize: 32_000,
          cacheableInputFraction: 0.4,
          stackComponents: [
            {
              id: "web-search",
              name: "Web Search + Scraping",
              category: "search",
              avgInputTokens: 0,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 4,
              fixedCostPerCall: 0.001,
            },
            {
              id: "research-llm",
              name: "Research Analysis (GPT-4.1 Mini)",
              category: "llm",
              modelId: "gpt-4.1-mini",
              avgInputTokens: 4500,
              avgOutputTokens: 1500,
              cacheable: true,
              cacheHitRate: 0.4,
              callsPerInvocation: 4,
            },
          ],
        },
        {
          id: "synthesizer",
          name: "Research Synthesizer",
          modelId: "claude-sonnet-4",
          role: "evaluator",
          avgStepsPerTask: 1,
          avgToolCallsPerStep: 0,
          toolDefinitionCount: 0,
          systemPromptTokens: 1500,
          avgInputTokensPerStep: 8000,
          avgOutputTokensPerStep: 2000,
          reflectionPasses: 1,
          contextStrategy: "stateless",
          cacheableInputFraction: 0.3,
          stackComponents: [
            {
              id: "synthesis",
              name: "Result Synthesis (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 9500,
              avgOutputTokens: 2000,
              cacheable: true,
              cacheHitRate: 0.3,
              callsPerInvocation: 2,
            },
          ],
        },
      ],
      orchestratorAgentId: "planner",
      parallelBranches: 2,
      errorRetryRate: 0.05,
      orchestrationOverheadTokens: 200,
    },
    usage: { tasksPerDay: 50, usersCount: 5, daysPerMonth: 22 },
    infra: {
      vectorDbMonthlyCost: 0,
      observabilityMonthlyCost: 40,
      computeMonthlyCost: 0,
      customItems: [{ id: "serp-api", name: "SERP API", monthlyCost: 50 }],
    },
  },

  // ─── Code Review Agent ───
  {
    id: "code-review-agent",
    name: "Code Review Agent",
    description:
      "Iterative code review with architect planning, coding, review, and testing phases.",
    costMetricLabel: "Cost per PR review",
    workflow: {
      pattern: "iterative-loop",
      agents: [
        {
          id: "reviewer",
          name: "Code Reviewer",
          modelId: "claude-sonnet-4",
          role: "evaluator",
          avgStepsPerTask: 3,
          avgToolCallsPerStep: 4,
          toolDefinitionCount: 8,
          systemPromptTokens: 2500,
          avgInputTokensPerStep: 5000,
          avgOutputTokensPerStep: 1500,
          reflectionPasses: 1,
          contextStrategy: "full-history",
          cacheableInputFraction: 0.4,
          stackComponents: [
            {
              id: "file-read",
              name: "File Reading + Context",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 8000,
              avgOutputTokens: 500,
              cacheable: true,
              cacheHitRate: 0.5,
              callsPerInvocation: 4,
            },
            {
              id: "review-analysis",
              name: "Review Analysis (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 6000,
              avgOutputTokens: 1500,
              cacheable: true,
              cacheHitRate: 0.4,
              callsPerInvocation: 3,
            },
            {
              id: "test-gen",
              name: "Test Suggestions",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 4000,
              avgOutputTokens: 2000,
              cacheable: true,
              cacheHitRate: 0.3,
              callsPerInvocation: 1,
            },
          ],
        },
      ],
      avgIterations: 2,
      errorRetryRate: 0.05,
      orchestrationOverheadTokens: 100,
    },
    usage: { tasksPerDay: 10, usersCount: 5, daysPerMonth: 22 },
    infra: {
      vectorDbMonthlyCost: 0,
      observabilityMonthlyCost: 30,
      computeMonthlyCost: 0,
      customItems: [],
    },
  },

  // ─── Customer Support Bot ───
  {
    id: "customer-support",
    name: "Customer Support Bot",
    description:
      "Two-stage: intent classification with cheap model, then response generation with capable model.",
    costMetricLabel: "Cost per support ticket",
    workflow: {
      pattern: "sequential",
      agents: [
        {
          id: "classifier",
          name: "Intent Classifier",
          modelId: "claude-haiku-3.5",
          role: "classifier",
          avgStepsPerTask: 1,
          avgToolCallsPerStep: 0,
          toolDefinitionCount: 0,
          systemPromptTokens: 600,
          avgInputTokensPerStep: 300,
          avgOutputTokensPerStep: 50,
          reflectionPasses: 0,
          contextStrategy: "stateless",
          cacheableInputFraction: 0.9,
          stackComponents: [
            {
              id: "classify",
              name: "Intent Classification (Haiku)",
              category: "routing",
              modelId: "claude-haiku-3.5",
              avgInputTokens: 900,
              avgOutputTokens: 50,
              cacheable: true,
              cacheHitRate: 0.9,
              callsPerInvocation: 1,
            },
          ],
        },
        {
          id: "responder",
          name: "Response Generator",
          modelId: "claude-sonnet-4",
          role: "worker",
          avgStepsPerTask: 2,
          avgToolCallsPerStep: 1,
          toolDefinitionCount: 5,
          systemPromptTokens: 1800,
          avgInputTokensPerStep: 1500,
          avgOutputTokensPerStep: 500,
          reflectionPasses: 0,
          contextStrategy: "full-history",
          cacheableInputFraction: 0.5,
          stackComponents: [
            {
              id: "kb-search",
              name: "Knowledge Base Search",
              category: "search",
              avgInputTokens: 0,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
              fixedCostPerCall: 0.00005,
            },
            {
              id: "response",
              name: "Response Generation (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 3300,
              avgOutputTokens: 500,
              cacheable: true,
              cacheHitRate: 0.5,
              callsPerInvocation: 2,
            },
          ],
        },
      ],
      errorRetryRate: 0.02,
      orchestrationOverheadTokens: 50,
    },
    usage: { tasksPerDay: 500, usersCount: 200, daysPerMonth: 30 },
    infra: {
      vectorDbMonthlyCost: 25,
      observabilityMonthlyCost: 20,
      computeMonthlyCost: 0,
      customItems: [],
    },
  },

  // ─── Simple RAG Chatbot ───
  {
    id: "simple-rag",
    name: "Simple RAG Chatbot",
    description:
      "Basic retrieval-augmented generation: embed query, search vectors, generate response.",
    costMetricLabel: "Cost per chat message",
    workflow: {
      pattern: "sequential",
      agents: [
        {
          id: "rag-bot",
          name: "RAG Chatbot",
          modelId: "gpt-4.1-mini",
          role: "worker",
          avgStepsPerTask: 1,
          avgToolCallsPerStep: 1,
          toolDefinitionCount: 2,
          systemPromptTokens: 1000,
          avgInputTokensPerStep: 1500,
          avgOutputTokensPerStep: 500,
          reflectionPasses: 0,
          contextStrategy: "sliding-window",
          slidingWindowSize: 16_000,
          cacheableInputFraction: 0.6,
          stackComponents: [
            {
              id: "embedding",
              name: "Query Embedding",
              category: "embedding",
              modelId: "text-embedding-3-small",
              avgInputTokens: 200,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
            },
            {
              id: "search",
              name: "Vector Search",
              category: "search",
              avgInputTokens: 0,
              avgOutputTokens: 0,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 1,
              fixedCostPerCall: 0.00005,
            },
            {
              id: "generation",
              name: "Response Generation (GPT-4.1 Mini)",
              category: "llm",
              modelId: "gpt-4.1-mini",
              avgInputTokens: 2500,
              avgOutputTokens: 500,
              cacheable: true,
              cacheHitRate: 0.6,
              callsPerInvocation: 1,
            },
          ],
        },
      ],
      errorRetryRate: 0.01,
      orchestrationOverheadTokens: 0,
    },
    usage: { tasksPerDay: 1000, usersCount: 100, daysPerMonth: 30 },
    infra: {
      vectorDbMonthlyCost: 25,
      observabilityMonthlyCost: 0,
      computeMonthlyCost: 0,
      customItems: [],
    },
  },

  // ─── Autonomous Software Engineer ───
  {
    id: "auto-swe",
    name: "Autonomous Software Engineer",
    description:
      "Full autonomous coding agent: plan → code → review → test. Hierarchical + iterative.",
    costMetricLabel: "Cost per feature implementation",
    workflow: {
      pattern: "hierarchical",
      agents: [
        {
          id: "architect",
          name: "Architect / Planner",
          modelId: "claude-opus-4",
          role: "orchestrator",
          avgStepsPerTask: 3,
          avgToolCallsPerStep: 2,
          toolDefinitionCount: 6,
          systemPromptTokens: 3000,
          avgInputTokensPerStep: 5000,
          avgOutputTokensPerStep: 2000,
          reflectionPasses: 1,
          contextStrategy: "full-history",
          cacheableInputFraction: 0.4,
          stackComponents: [
            {
              id: "planning",
              name: "Architecture Planning (Opus 4)",
              category: "llm",
              modelId: "claude-opus-4",
              avgInputTokens: 8000,
              avgOutputTokens: 2000,
              cacheable: true,
              cacheHitRate: 0.5,
              callsPerInvocation: 4,
            },
          ],
        },
        {
          id: "coder",
          name: "Code Generator",
          modelId: "claude-sonnet-4",
          role: "worker",
          avgStepsPerTask: 8,
          avgToolCallsPerStep: 4,
          toolDefinitionCount: 10,
          systemPromptTokens: 2500,
          avgInputTokensPerStep: 4000,
          avgOutputTokensPerStep: 2000,
          reflectionPasses: 1,
          contextStrategy: "sliding-window",
          slidingWindowSize: 64_000,
          cacheableInputFraction: 0.3,
          stackComponents: [
            {
              id: "file-ops",
              name: "File Read/Write (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 6000,
              avgOutputTokens: 2000,
              cacheable: true,
              cacheHitRate: 0.3,
              callsPerInvocation: 10,
            },
            {
              id: "code-exec",
              name: "Code Execution Feedback",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 3000,
              avgOutputTokens: 500,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 4,
            },
          ],
        },
        {
          id: "reviewer-agent",
          name: "Code Reviewer",
          modelId: "claude-sonnet-4",
          role: "evaluator",
          avgStepsPerTask: 2,
          avgToolCallsPerStep: 3,
          toolDefinitionCount: 5,
          systemPromptTokens: 2000,
          avgInputTokensPerStep: 6000,
          avgOutputTokensPerStep: 1500,
          reflectionPasses: 0,
          contextStrategy: "stateless",
          cacheableInputFraction: 0.4,
          stackComponents: [
            {
              id: "review",
              name: "Code Review (Sonnet 4)",
              category: "llm",
              modelId: "claude-sonnet-4",
              avgInputTokens: 8000,
              avgOutputTokens: 1500,
              cacheable: true,
              cacheHitRate: 0.4,
              callsPerInvocation: 2,
            },
          ],
        },
        {
          id: "tester",
          name: "Test Generator",
          modelId: "gpt-4.1-mini",
          role: "worker",
          avgStepsPerTask: 3,
          avgToolCallsPerStep: 2,
          toolDefinitionCount: 4,
          systemPromptTokens: 1500,
          avgInputTokensPerStep: 3000,
          avgOutputTokensPerStep: 2000,
          reflectionPasses: 0,
          contextStrategy: "sliding-window",
          slidingWindowSize: 32_000,
          cacheableInputFraction: 0.4,
          stackComponents: [
            {
              id: "test-gen",
              name: "Test Generation (GPT-4.1 Mini)",
              category: "llm",
              modelId: "gpt-4.1-mini",
              avgInputTokens: 4500,
              avgOutputTokens: 2000,
              cacheable: true,
              cacheHitRate: 0.4,
              callsPerInvocation: 3,
            },
            {
              id: "test-exec",
              name: "Test Execution Feedback",
              category: "llm",
              modelId: "gpt-4.1-mini",
              avgInputTokens: 2000,
              avgOutputTokens: 300,
              cacheable: false,
              cacheHitRate: 0,
              callsPerInvocation: 3,
            },
          ],
        },
      ],
      orchestratorAgentId: "architect",
      errorRetryRate: 0.08,
      orchestrationOverheadTokens: 300,
    },
    usage: { tasksPerDay: 5, usersCount: 3, daysPerMonth: 22 },
    infra: {
      vectorDbMonthlyCost: 0,
      observabilityMonthlyCost: 50,
      computeMonthlyCost: 100,
      customItems: [],
    },
  },
];

export function getPresetById(id: string): WorkflowPreset | undefined {
  return WORKFLOW_PRESETS.find((p) => p.id === id);
}
